services:
    app.form.type.add_or_select:
        class: gtrias\AddOrSelectBundle\Form\Type\AddOrSelectType
        arguments: ['@doctrine']
        tags:
            - { name: form.type, alias: gtrias_addorselect }
    gtrias.twig.extension.form:
        class: gtrias\AddOrSelectBundle\Twig\Extension\FormExtension
        arguments: ['@twig.form.renderer']
        tags:
            - { name: twig.extension}
